# Site settings
title: inclusa
email: inclusa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: /inclusa.github.io # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: inclusa
github_username:  inclusa

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 10
paginate_path: "/blog/page:num"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

# Gems
gems: [jekyll-paginate]
