# Site settings
title: inclusa
email: inclusa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://inclusa.github.io/"  # the base hostname & protocol for your site
twitter_username: inclusa
github_username:  inclusa

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 100
paginate_path: "/blog/page:num"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
  productivity:
    output: true
    permalink: /productivity/:path/

# Gems
gems: [jekyll-paginate]

# Port
port: 4001 # Canvia el port del server al 4001
